model = "gpt-5.2-codex"
approval_policy = "on-failure"
sandbox_mode    = "workspace-write"
tool_output_token_limit = 25000
# 273000 - (25000 + 15000), where 25000 is tool output limit and 15000 is buffer for prompt and response
model_auto_compact_token_limit = 233000
model_reasoning_effort = "high"
model_reasoning_summary = "auto"

[features]
web_search_request = true
apply_patch_freeform = true
unified_exec = true

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
