model = "gpt-5.3-codex"
sandbox_mode    = "danger-full-access"
approval_policy = "never"
tool_output_token_limit = 15000
# 273000 - (15000 + 15000), where 15000 is tool output limit and 15000 is buffer for prompt and response
model_auto_compact_token_limit = 243000
model_reasoning_effort = "high"
model_reasoning_summary = "auto"
web_search = "live"
personality = "pragmatic"
suppress_unstable_features_warning = true

[features]
shell_snapshot = true
steer = true
multi_agent = true
voice_transcription = true

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
"gpt-5.2" = "gpt-5.2-codex"
